sudo: required
services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t react_image .

script:
  - docker container run -e CI=true react_image npm run test

deploy:
  provider: "elasticbeanstalk"
  region: "ap-southeast-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-ap-southeast-2-975050095560"
  bucket_path: "frontend"
  on:
    branch: "master"
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
